{{- if eq .Values.global.deploymentMode "development" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    {{ template "admin-routes.whitelist.annotation" . }}
  name: {{ .Values.redash.instance.name.admin }}
spec:
  host: {{ .Values.redash.instance.name.admin }}-{{ .Release.Namespace }}.{{ .Values.dnsWildcard }}
  to:
    kind: Service
    name: {{ .Values.redash.instance.name.admin }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
status:
  ingress: []
{{- end }}
