{{- if eq .Values.global.deploymentMode "development" }}
apiVersion: v1
kind: Service
metadata:
  name: admin-tools-{{ .Values.redash.instance.name.admin }}
  annotations:
    ingress.kubernetes.io/service-upstream: 'true'
    konghq.com/override: kong-admin-tools-set-timeouts
    konghq.com/path: /
    konghq.com/protocol: http
  labels:
    helm.sh/chart: {{ .Values.redash.instance.name.admin }}-2.3.0
    app.kubernetes.io/name: {{ .Values.redash.instance.name.admin }}
    app.kubernetes.io/instance: {{ .Values.redash.instance.name.admin }}
    app.kubernetes.io/version: {{ .Values.redash.version | squote }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: server
spec:
  ports:
    - name: http
      port: {{ .Values.server.httpPort }}
      protocol: TCP
      targetPort: {{ .Values.server.httpPort }}
  selector:
    app.kubernetes.io/name: {{ .Values.redash.instance.name.admin }}
    app.kubernetes.io/instance: {{ .Values.redash.instance.name.admin }}
    app.kubernetes.io/component: server
  sessionAffinity: None
  type: ClusterIP
{{- end }}