kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.exporter.name }}
  labels:
    app: {{ .Values.exporter.name }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  selector:
    app: {{ .Values.exporter.name }}
  type: ClusterIP