apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redash.existingSecret }}
  annotations:
    "helm.sh/hook": "pre-install"
type: Opaque
data:
  secretKey: {{ randAlphaNum 64 | b64enc | quote }}
  cookieSecret: {{ randAlphaNum 64 | b64enc | quote }}
  postgresqlPassword: {{ randAlphaNum 32 | b64enc | quote }}
  googleClientSecret: "bm90c2V0"
  ldapBindDnPassword: "bm90c2V0"
  mailPassword: "bm90c2V0"
