apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.redash.instance.name.viewer }}-db-wait"
  labels:
    helm.sh/chart: {{ .Values.redash.instance.name.viewer }}-2.3.0
    app.kubernetes.io/name: {{ .Values.redash.instance.name.viewer }}
    app.kubernetes.io/instance: {{ .Values.redash.instance.name.viewer }}
    app.kubernetes.io/version: {{ .Values.redash.version | squote }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: upgrade
  annotations:
    # This is what defines this resource as a hook.
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Values.redash.instance.name.viewer }}
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app.kubernetes.io/name: {{ .Values.redash.instance.name.viewer }}
        app.kubernetes.io/instance: {{ .Values.redash.instance.name.viewer }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      restartPolicy: Never
      containers:
        - name: {{ .Values.redash.instance.name.viewer }}-server
          image: "{{ .Values.image.name }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash"]
          args:
            - -c
            - echo "done"
          volumeMounts:
            - name: indicator
              mountPath: /config
      volumes:
        - name: indicator
          configMap:
            name: migration-indicator-{{ .Values.redash.instance.name.viewer }}
  {{- with .Values.server.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.server.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.server.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
  {{- end }}
