apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.redash.instance.name.viewer }}
spec:
  host: {{ .Values.redash.instance.name.viewer }}-{{ .Values.namespace }}.{{ .Values.dnsWildcard }}
  to:
    kind: Service
    name: {{ .Values.redash.instance.name.viewer }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
status:
  ingress: []
